name: Update and Publish CSV

on:
  schedule:
    - cron: '*/10 * * * *'  # Run every 10 minutes

jobs:
  update-csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update CSV
        run: |
          curl -LJb 'https://drive.google.com/uc?export=download&id=13YcQYdXEI2s-rJW4Bmskz7458mCIw56y' -o data.csv


      - name: Commit Changes
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add data.csv
          git commit -m "Auto-update CSV [skip ci]"

      - name: Push Changes
        run: |
          git push

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # The root directory containing data.csv
